//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SixthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buildings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buildings()
        {
            this.Rooms = new HashSet<Rooms>();
        }
    
        public byte Letter { get; set; }
        public int DomicileID { get; set; }
        public string Contents { get; set; }
        public int TypeID { get; set; }
        public bool MySelf { get; set; }
        public short Year { get; set; }
        public double SquareAll { get; set; }
        public double Inhabited { get; set; }
        public byte Wear { get; set; }
        public string Wall { get; set; }
        public decimal Cost { get; set; }
        public int Storeys { get; set; }
    
        public virtual Domicile Domicile { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rooms> Rooms { get; set; }
    }
}
