//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SixthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Domicile()
        {
            this.Buildings = new HashSet<Buildings>();
        }
    
        public int ID { get; set; }
        public string Block { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public System.DateTime Inventory { get; set; }
        public double Land { get; set; }
        public double Actual { get; set; }
        public double BuildUp { get; set; }
        public double Yard { get; set; }
        public double Green { get; set; }
        public double Garden { get; set; }
        public double Bad { get; set; }
        public byte[] Picture { get; set; }
        public bool Light { get; set; }
        public bool WaterPipe { get; set; }
        public bool Heating { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buildings> Buildings { get; set; }
    }
}
